---
title: "Reproducible Research: Peer Assessment 1"
output: 
html_document:
keep_md: true
---


## Loading and preprocessing the data

Loading the data:

```{R}

unzip('activity.zip')
activity <- read.csv('activity.csv',na.strings=c("NA", "NULL"))

```






## What is mean total number of steps taken per day?

Calculating the total number of steps taken per day:
```{R}
activityNoNA <- activity[complete.cases(activity),]
stepsPerDay <- tapply(activity$steps, activity$date, sum)
```

Making a histogram of the total number of steps taken each day:
```{R}
png("stepsPerDay.png")
hist(stepsPerDay, xlab= "Steps Per Day", main= " ", col=c("green"))
dev.off()
```

Calculating the mean and median of the total number of steps taken per day:
```{R}

mean <- mean(activityNoNA[,1])
median <- median(activityNoNA[,1])

```
_The mean is __`r mean`__ and the median is __`r median`__._



## What is the average daily activity pattern?

1. Making a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
```{R}

stepsInterval <- aggregate(steps ~ interval, data = activityNoNA, FUN = "mean")
 png("figures/dailyActivity.png")
plot(stepsInterval, type="l",xlab="Interval", ylab="Steps", col=c("red"), main = "Daily Activity Pattern")
interval = stepsInterval$interval[which.max(stepsInterval$steps)]
dev.off()
```



2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

_The 5-minute interval that contains the maximum number of steps is the __`r interval`th__._








## Imputing missing values
1. Calculating the total number of missing values in the dataset:
```{R}
valuesMissing <- sum(is.na(activity))
```

_The number of missing values is __`r valuesMissing`__._


2. Devising a strategy for filling in all of the missing values in the dataset:

_The missing values will be replaced by the mean based on its interval._

3. Creating the new database:
```{R}

stepsInterval <- aggregate(steps ~ interval, data = activityNoNA, FUN = "mean")
activityFilled <- activity 
for (i in 1:nrow(activityFilled)) {
if (is.na(activityFilled[ i ,1]))
{
int <- activityFilled[i,3]
x <-   stepsInterval[(stepsInterval$interval == int),2]
activityFilled[i,1] <- x
}

}
summary(activityFilled)
 ```
 
4. Making a histogram of the total number of steps taken each day and calculating the mean and median total number of steps taken per day. 


```{R}
mean <- mean(activityFilled[,1])
median <- median(activityFilled[,1])
stepsPerDay <- tapply(activityFilled$steps, activityFilled$date, sum)
png("stepsPerDayNonoise.png")
hist(stepsPerDay, xlab= "Steps Per Day", main="After Filling NA Values with Means",col=c("yellow"))
dev.off()
```

####Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

The values of steps per day have risen notably after the missing values were replaced with the mean.











## Are there differences in activity patterns between weekdays and weekends?
_Based on the steps below, there is observable differences between the two._

 1. Creating a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.
 
```{R}
activityFilled$day <- activityFilled$date
class(activityFilled$day) <- as.factor(activityFilled$day)

activityFilled$day <- weekdays(as.Date(activityFilled$date))

activityFilled$daytype <- ifelse(activityFilled$day %in% c("Monday", "Tuesday", "Wednesday","Thursday", "Friday"), "weekday", "weekend")


 activityWeekdays <- activityFilled[activityFilled$day %in% c("Monday", "Tuesday", "Wednesday","Thursday", "Friday"),]
activityWeekends <- activityFilled[activityFilled$day %in% c("Sunday",  "Saturday"), ]
stepsIntervalWeekdays <- aggregate(steps ~ interval, data = activityWeekdays, FUN = "mean")
stepsIntervalWeekends <- aggregate(steps ~ interval, data = activityWeekends, FUN = "mean")
```


2. Making a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis).


 ```{R}
 png("figures/DayTypes.png")
par(mfrow=c(2,1))
par(mar=c(0.5, 4.5, 0.5, 0.5))
plot(stepsIntervalWeekdays$interval, stepsIntervalWeekdays$steps, type="l",ylab="", xaxt='n', ann=TRUE , col=c("blue"))
title(main="Daily Activity for Weekdays", line = -1)
plot(stepsIntervalWeekends$interval, stepsIntervalWeekends$steps, type="l",ylab="",  xaxt='n',ann=TRUE,col=c("blue") )
title(main="Daily Activity for Weekends",line = -1)
dev.off()
```
 
 


